"""
Parameter (name=backbone.conv1._conv.weight, shape=(32, 17, 1, 7, 7), dtype=Float32, requires_grad=True)
Parameter (name=backbone.conv1._batch_norm.bn2d.gamma, shape=(32,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.conv1._batch_norm.bn2d.beta, shape=(32,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.0.conv1._conv.weight, shape=(32, 32, 1, 1, 1), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.0.conv1._batch_norm.bn2d.gamma, shape=(32,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.0.conv1._batch_norm.bn2d.beta, shape=(32,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.0.conv2._conv.weight, shape=(32, 32, 1, 3, 3), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.0.conv2._batch_norm.bn2d.gamma, shape=(32,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.0.conv2._batch_norm.bn2d.beta, shape=(32,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.0.conv3._conv.weight, shape=(128, 32, 1, 1, 1), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.0.conv3._batch_norm.bn2d.gamma, shape=(128,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.0.conv3._batch_norm.bn2d.beta, shape=(128,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.0.downsample._conv.weight, shape=(128, 32, 1, 1, 1), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.0.downsample._batch_norm.bn2d.gamma, shape=(128,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.0.downsample._batch_norm.bn2d.beta, shape=(128,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.1.conv1._conv.weight, shape=(32, 128, 1, 1, 1), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.1.conv1._batch_norm.bn2d.gamma, shape=(32,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.1.conv1._batch_norm.bn2d.beta, shape=(32,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.1.conv2._conv.weight, shape=(32, 32, 1, 3, 3), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.1.conv2._batch_norm.bn2d.gamma, shape=(32,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.1.conv2._batch_norm.bn2d.beta, shape=(32,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.1.conv3._conv.weight, shape=(128, 32, 1, 1, 1), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.1.conv3._batch_norm.bn2d.gamma, shape=(128,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.1.conv3._batch_norm.bn2d.beta, shape=(128,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.2.conv1._conv.weight, shape=(32, 128, 1, 1, 1), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.2.conv1._batch_norm.bn2d.gamma, shape=(32,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.2.conv1._batch_norm.bn2d.beta, shape=(32,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.2.conv2._conv.weight, shape=(32, 32, 1, 3, 3), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.2.conv2._batch_norm.bn2d.gamma, shape=(32,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.2.conv2._batch_norm.bn2d.beta, shape=(32,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.2.conv3._conv.weight, shape=(128, 32, 1, 1, 1), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.2.conv3._batch_norm.bn2d.gamma, shape=(128,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.2.conv3._batch_norm.bn2d.beta, shape=(128,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.3.conv1._conv.weight, shape=(32, 128, 1, 1, 1), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.3.conv1._batch_norm.bn2d.gamma, shape=(32,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.3.conv1._batch_norm.bn2d.beta, shape=(32,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.3.conv2._conv.weight, shape=(32, 32, 1, 3, 3), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.3.conv2._batch_norm.bn2d.gamma, shape=(32,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.3.conv2._batch_norm.bn2d.beta, shape=(32,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.3.conv3._conv.weight, shape=(128, 32, 1, 1, 1), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.3.conv3._batch_norm.bn2d.gamma, shape=(128,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.0.3.conv3._batch_norm.bn2d.beta, shape=(128,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.0.conv1._conv.weight, shape=(64, 128, 3, 1, 1), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.0.conv1._batch_norm.bn2d.gamma, shape=(64,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.0.conv1._batch_norm.bn2d.beta, shape=(64,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.0.conv2._conv.weight, shape=(64, 64, 1, 3, 3), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.0.conv2._batch_norm.bn2d.gamma, shape=(64,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.0.conv2._batch_norm.bn2d.beta, shape=(64,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.0.conv3._conv.weight, shape=(256, 64, 1, 1, 1), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.0.conv3._batch_norm.bn2d.gamma, shape=(256,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.0.conv3._batch_norm.bn2d.beta, shape=(256,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.0.downsample._conv.weight, shape=(256, 128, 1, 1, 1), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.0.downsample._batch_norm.bn2d.gamma, shape=(256,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.0.downsample._batch_norm.bn2d.beta, shape=(256,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.1.conv1._conv.weight, shape=(64, 256, 3, 1, 1), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.1.conv1._batch_norm.bn2d.gamma, shape=(64,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.1.conv1._batch_norm.bn2d.beta, shape=(64,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.1.conv2._conv.weight, shape=(64, 64, 1, 3, 3), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.1.conv2._batch_norm.bn2d.gamma, shape=(64,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.1.conv2._batch_norm.bn2d.beta, shape=(64,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.1.conv3._conv.weight, shape=(256, 64, 1, 1, 1), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.1.conv3._batch_norm.bn2d.gamma, shape=(256,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.1.conv3._batch_norm.bn2d.beta, shape=(256,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.2.conv1._conv.weight, shape=(64, 256, 3, 1, 1), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.2.conv1._batch_norm.bn2d.gamma, shape=(64,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.2.conv1._batch_norm.bn2d.beta, shape=(64,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.2.conv2._conv.weight, shape=(64, 64, 1, 3, 3), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.2.conv2._batch_norm.bn2d.gamma, shape=(64,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.2.conv2._batch_norm.bn2d.beta, shape=(64,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.2.conv3._conv.weight, shape=(256, 64, 1, 1, 1), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.2.conv3._batch_norm.bn2d.gamma, shape=(256,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.2.conv3._batch_norm.bn2d.beta, shape=(256,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.3.conv1._conv.weight, shape=(64, 256, 3, 1, 1), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.3.conv1._batch_norm.bn2d.gamma, shape=(64,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.3.conv1._batch_norm.bn2d.beta, shape=(64,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.3.conv2._conv.weight, shape=(64, 64, 1, 3, 3), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.3.conv2._batch_norm.bn2d.gamma, shape=(64,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.3.conv2._batch_norm.bn2d.beta, shape=(64,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.3.conv3._conv.weight, shape=(256, 64, 1, 1, 1), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.3.conv3._batch_norm.bn2d.gamma, shape=(256,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.3.conv3._batch_norm.bn2d.beta, shape=(256,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.4.conv1._conv.weight, shape=(64, 256, 3, 1, 1), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.4.conv1._batch_norm.bn2d.gamma, shape=(64,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.4.conv1._batch_norm.bn2d.beta, shape=(64,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.4.conv2._conv.weight, shape=(64, 64, 1, 3, 3), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.4.conv2._batch_norm.bn2d.gamma, shape=(64,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.4.conv2._batch_norm.bn2d.beta, shape=(64,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.4.conv3._conv.weight, shape=(256, 64, 1, 1, 1), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.4.conv3._batch_norm.bn2d.gamma, shape=(256,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.4.conv3._batch_norm.bn2d.beta, shape=(256,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.5.conv1._conv.weight, shape=(64, 256, 3, 1, 1), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.5.conv1._batch_norm.bn2d.gamma, shape=(64,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.5.conv1._batch_norm.bn2d.beta, shape=(64,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.5.conv2._conv.weight, shape=(64, 64, 1, 3, 3), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.5.conv2._batch_norm.bn2d.gamma, shape=(64,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.5.conv2._batch_norm.bn2d.beta, shape=(64,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.5.conv3._conv.weight, shape=(256, 64, 1, 1, 1), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.5.conv3._batch_norm.bn2d.gamma, shape=(256,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.1.5.conv3._batch_norm.bn2d.beta, shape=(256,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.2.0.conv1._conv.weight, shape=(128, 256, 3, 1, 1), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.2.0.conv1._batch_norm.bn2d.gamma, shape=(128,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.2.0.conv1._batch_norm.bn2d.beta, shape=(128,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.2.0.conv2._conv.weight, shape=(128, 128, 1, 3, 3), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.2.0.conv2._batch_norm.bn2d.gamma, shape=(128,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.2.0.conv2._batch_norm.bn2d.beta, shape=(128,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.2.0.conv3._conv.weight, shape=(512, 128, 1, 1, 1), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.2.0.conv3._batch_norm.bn2d.gamma, shape=(512,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.2.0.conv3._batch_norm.bn2d.beta, shape=(512,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.2.0.downsample._conv.weight, shape=(512, 256, 1, 1, 1), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.2.0.downsample._batch_norm.bn2d.gamma, shape=(512,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.2.0.downsample._batch_norm.bn2d.beta, shape=(512,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.2.1.conv1._conv.weight, shape=(128, 512, 3, 1, 1), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.2.1.conv1._batch_norm.bn2d.gamma, shape=(128,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.2.1.conv1._batch_norm.bn2d.beta, shape=(128,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.2.1.conv2._conv.weight, shape=(128, 128, 1, 3, 3), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.2.1.conv2._batch_norm.bn2d.gamma, shape=(128,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.2.1.conv2._batch_norm.bn2d.beta, shape=(128,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.2.1.conv3._conv.weight, shape=(512, 128, 1, 1, 1), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.2.1.conv3._batch_norm.bn2d.gamma, shape=(512,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.2.1.conv3._batch_norm.bn2d.beta, shape=(512,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.2.2.conv1._conv.weight, shape=(128, 512, 3, 1, 1), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.2.2.conv1._batch_norm.bn2d.gamma, shape=(128,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.2.2.conv1._batch_norm.bn2d.beta, shape=(128,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.2.2.conv2._conv.weight, shape=(128, 128, 1, 3, 3), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.2.2.conv2._batch_norm.bn2d.gamma, shape=(128,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.2.2.conv2._batch_norm.bn2d.beta, shape=(128,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.2.2.conv3._conv.weight, shape=(512, 128, 1, 1, 1), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.2.2.conv3._batch_norm.bn2d.gamma, shape=(512,), dtype=Float32, requires_grad=True)
Parameter (name=backbone.res_layers.2.2.conv3._batch_norm.bn2d.beta, shape=(512,), dtype=Float32, requires_grad=True)
Parameter (name=head.fc_cls.weight, shape=(60, 512), dtype=Float32, requires_grad=True)
Parameter (name=head.fc_cls.bias, shape=(60,), dtype=Float32, requires_grad=True)

"""