"""
backbone.data_bnc.moving_mean
backbone.data_bnc.moving_variance
backbone.data_bnc.gamma
backbone.data_bnc.beta

backbone.gcn.0.gcn.A
backbone.gcn.0.gcn.PA
backbone.gcn.0.gcn.conv.weight
backbone.gcn.0.gcn.conv.bias
backbone.gcn.0.gcn.bn.moving_mean
backbone.gcn.0.gcn.bn.moving_variance
backbone.gcn.0.gcn.bn.gamma
backbone.gcn.0.gcn.bn.beta
backbone.gcn.0.tcn.conv.weight
backbone.gcn.0.tcn.conv.bias
backbone.gcn.0.tcn.bn.moving_mean
backbone.gcn.0.tcn.bn.moving_variance
backbone.gcn.0.tcn.bn.gamma
backbone.gcn.0.tcn.bn.beta

backbone.gcn.1.gcn.A
backbone.gcn.1.gcn.PA
backbone.gcn.1.gcn.conv.weight
backbone.gcn.1.gcn.conv.bias
backbone.gcn.1.gcn.bn.moving_mean
backbone.gcn.1.gcn.bn.moving_variance
backbone.gcn.1.gcn.bn.gamma
backbone.gcn.1.gcn.bn.beta
backbone.gcn.1.tcn.conv.weight
backbone.gcn.1.tcn.conv.bias
backbone.gcn.1.tcn.bn.moving_mean
backbone.gcn.1.tcn.bn.moving_variance
backbone.gcn.1.tcn.bn.gamma
backbone.gcn.1.tcn.bn.beta

backbone.gcn.2.gcn.A
backbone.gcn.2.gcn.PA
backbone.gcn.2.gcn.conv.weight
backbone.gcn.2.gcn.conv.bias
backbone.gcn.2.gcn.bn.moving_mean
backbone.gcn.2.gcn.bn.moving_variance
backbone.gcn.2.gcn.bn.gamma
backbone.gcn.2.gcn.bn.beta
backbone.gcn.2.tcn.conv.weight
backbone.gcn.2.tcn.conv.bias
backbone.gcn.2.tcn.bn.moving_mean
backbone.gcn.2.tcn.bn.moving_variance
backbone.gcn.2.tcn.bn.gamma
backbone.gcn.2.tcn.bn.beta

backbone.gcn.3.gcn.A
backbone.gcn.3.gcn.PA
backbone.gcn.3.gcn.conv.weight
backbone.gcn.3.gcn.conv.bias
backbone.gcn.3.gcn.bn.moving_mean
backbone.gcn.3.gcn.bn.moving_variance
backbone.gcn.3.gcn.bn.gamma
backbone.gcn.3.gcn.bn.beta
backbone.gcn.3.tcn.conv.weight
backbone.gcn.3.tcn.conv.bias
backbone.gcn.3.tcn.bn.moving_mean
backbone.gcn.3.tcn.bn.moving_variance
backbone.gcn.3.tcn.bn.gamma
backbone.gcn.3.tcn.bn.beta

backbone.gcn.4.gcn.A
backbone.gcn.4.gcn.PA
backbone.gcn.4.gcn.conv.weight
backbone.gcn.4.gcn.conv.bias
backbone.gcn.4.gcn.bn.moving_mean
backbone.gcn.4.gcn.bn.moving_variance
backbone.gcn.4.gcn.bn.gamma
backbone.gcn.4.gcn.bn.beta
backbone.gcn.4.tcn.conv.weight
backbone.gcn.4.tcn.conv.bias
backbone.gcn.4.tcn.bn.moving_mean
backbone.gcn.4.tcn.bn.moving_variance
backbone.gcn.4.tcn.bn.gamma
backbone.gcn.4.tcn.bn.beta

backbone.gcn.4.residual.conv.weight
backbone.gcn.4.residual.conv.bias
backbone.gcn.4.residual.bn.moving_mean
backbone.gcn.4.residual.bn.moving_variance
backbone.gcn.4.residual.bn.gamma
backbone.gcn.4.residual.bn.beta

backbone.gcn.5.gcn.A
backbone.gcn.5.gcn.PA
backbone.gcn.5.gcn.conv.weight
backbone.gcn.5.gcn.conv.bias
backbone.gcn.5.gcn.bn.moving_mean
backbone.gcn.5.gcn.bn.moving_variance
backbone.gcn.5.gcn.bn.gamma
backbone.gcn.5.gcn.bn.beta
backbone.gcn.5.tcn.conv.weight
backbone.gcn.5.tcn.conv.bias
backbone.gcn.5.tcn.bn.moving_mean
backbone.gcn.5.tcn.bn.moving_variance
backbone.gcn.5.tcn.bn.gamma
backbone.gcn.5.tcn.bn.beta

backbone.gcn.6.gcn.A
backbone.gcn.6.gcn.PA
backbone.gcn.6.gcn.conv.weight
backbone.gcn.6.gcn.conv.bias
backbone.gcn.6.gcn.bn.moving_mean
backbone.gcn.6.gcn.bn.moving_variance
backbone.gcn.6.gcn.bn.gamma
backbone.gcn.6.gcn.bn.beta
backbone.gcn.6.tcn.conv.weight
backbone.gcn.6.tcn.conv.bias
backbone.gcn.6.tcn.bn.moving_mean
backbone.gcn.6.tcn.bn.moving_variance
backbone.gcn.6.tcn.bn.gamma
backbone.gcn.6.tcn.bn.beta

backbone.gcn.7.gcn.A
backbone.gcn.7.gcn.PA
backbone.gcn.7.gcn.conv.weight
backbone.gcn.7.gcn.conv.bias
backbone.gcn.7.gcn.bn.moving_mean
backbone.gcn.7.gcn.bn.moving_variance
backbone.gcn.7.gcn.bn.gamma
backbone.gcn.7.gcn.bn.beta
backbone.gcn.7.tcn.conv.weight
backbone.gcn.7.tcn.conv.bias
backbone.gcn.7.tcn.bn.moving_mean
backbone.gcn.7.tcn.bn.moving_variance
backbone.gcn.7.tcn.bn.gamma
backbone.gcn.7.tcn.bn.beta

backbone.gcn.7.residual.conv.weight
backbone.gcn.7.residual.conv.bias
backbone.gcn.7.residual.bn.moving_mean
backbone.gcn.7.residual.bn.moving_variance
backbone.gcn.7.residual.bn.gamma
backbone.gcn.7.residual.bn.beta

backbone.gcn.8.gcn.A
backbone.gcn.8.gcn.PA
backbone.gcn.8.gcn.conv.weight
backbone.gcn.8.gcn.conv.bias
backbone.gcn.8.gcn.bn.moving_mean
backbone.gcn.8.gcn.bn.moving_variance
backbone.gcn.8.gcn.bn.gamma
backbone.gcn.8.gcn.bn.beta
backbone.gcn.8.tcn.conv.weight
backbone.gcn.8.tcn.conv.bias
backbone.gcn.8.tcn.bn.moving_mean
backbone.gcn.8.tcn.bn.moving_variance
backbone.gcn.8.tcn.bn.gamma
backbone.gcn.8.tcn.bn.beta

backbone.gcn.9.gcn.A
backbone.gcn.9.gcn.PA
backbone.gcn.9.gcn.conv.weight
backbone.gcn.9.gcn.conv.bias
backbone.gcn.9.gcn.bn.moving_mean
backbone.gcn.9.gcn.bn.moving_variance
backbone.gcn.9.gcn.bn.gamma
backbone.gcn.9.gcn.bn.beta
backbone.gcn.9.tcn.conv.weight
backbone.gcn.9.tcn.conv.bias
backbone.gcn.9.tcn.bn.moving_mean
backbone.gcn.9.tcn.bn.moving_variance
backbone.gcn.9.tcn.bn.gamma
backbone.gcn.9.tcn.bn.beta

head.fc.weight
head.fc.bias

"""