"""
backbone.conv1.conv.weight
backbone.conv1.bn.weight
backbone.conv1.bn.bias
backbone.conv1.bn.running_mean
backbone.conv1.bn.running_var
backbone.conv1.bn.num_batches_tracked
backbone.layer1.0.conv1.conv.weight
backbone.layer1.0.conv1.bn.weight
backbone.layer1.0.conv1.bn.bias
backbone.layer1.0.conv1.bn.running_mean
backbone.layer1.0.conv1.bn.running_var
backbone.layer1.0.conv1.bn.num_batches_tracked
backbone.layer1.0.conv2.conv.weight
backbone.layer1.0.conv2.bn.weight
backbone.layer1.0.conv2.bn.bias
backbone.layer1.0.conv2.bn.running_mean
backbone.layer1.0.conv2.bn.running_var
backbone.layer1.0.conv2.bn.num_batches_tracked
backbone.layer1.0.conv3.conv.weight
backbone.layer1.0.conv3.bn.weight
backbone.layer1.0.conv3.bn.bias
backbone.layer1.0.conv3.bn.running_mean
backbone.layer1.0.conv3.bn.running_var
backbone.layer1.0.conv3.bn.num_batches_tracked
backbone.layer1.0.downsample.conv.weight
backbone.layer1.0.downsample.bn.weight
backbone.layer1.0.downsample.bn.bias
backbone.layer1.0.downsample.bn.running_mean
backbone.layer1.0.downsample.bn.running_var
backbone.layer1.0.downsample.bn.num_batches_tracked
backbone.layer1.1.conv1.conv.weight
backbone.layer1.1.conv1.bn.weight
backbone.layer1.1.conv1.bn.bias
backbone.layer1.1.conv1.bn.running_mean
backbone.layer1.1.conv1.bn.running_var
backbone.layer1.1.conv1.bn.num_batches_tracked
backbone.layer1.1.conv2.conv.weight
backbone.layer1.1.conv2.bn.weight
backbone.layer1.1.conv2.bn.bias
backbone.layer1.1.conv2.bn.running_mean
backbone.layer1.1.conv2.bn.running_var
backbone.layer1.1.conv2.bn.num_batches_tracked
backbone.layer1.1.conv3.conv.weight
backbone.layer1.1.conv3.bn.weight
backbone.layer1.1.conv3.bn.bias
backbone.layer1.1.conv3.bn.running_mean
backbone.layer1.1.conv3.bn.running_var
backbone.layer1.1.conv3.bn.num_batches_tracked
backbone.layer1.2.conv1.conv.weight
backbone.layer1.2.conv1.bn.weight
backbone.layer1.2.conv1.bn.bias
backbone.layer1.2.conv1.bn.running_mean
backbone.layer1.2.conv1.bn.running_var
backbone.layer1.2.conv1.bn.num_batches_tracked
backbone.layer1.2.conv2.conv.weight
backbone.layer1.2.conv2.bn.weight
backbone.layer1.2.conv2.bn.bias
backbone.layer1.2.conv2.bn.running_mean
backbone.layer1.2.conv2.bn.running_var
backbone.layer1.2.conv2.bn.num_batches_tracked
backbone.layer1.2.conv3.conv.weight
backbone.layer1.2.conv3.bn.weight
backbone.layer1.2.conv3.bn.bias
backbone.layer1.2.conv3.bn.running_mean
backbone.layer1.2.conv3.bn.running_var
backbone.layer1.2.conv3.bn.num_batches_tracked
backbone.layer1.3.conv1.conv.weight
backbone.layer1.3.conv1.bn.weight
backbone.layer1.3.conv1.bn.bias
backbone.layer1.3.conv1.bn.running_mean
backbone.layer1.3.conv1.bn.running_var
backbone.layer1.3.conv1.bn.num_batches_tracked
backbone.layer1.3.conv2.conv.weight
backbone.layer1.3.conv2.bn.weight
backbone.layer1.3.conv2.bn.bias
backbone.layer1.3.conv2.bn.running_mean
backbone.layer1.3.conv2.bn.running_var
backbone.layer1.3.conv2.bn.num_batches_tracked
backbone.layer1.3.conv3.conv.weight
backbone.layer1.3.conv3.bn.weight
backbone.layer1.3.conv3.bn.bias
backbone.layer1.3.conv3.bn.running_mean
backbone.layer1.3.conv3.bn.running_var
backbone.layer1.3.conv3.bn.num_batches_tracked
backbone.layer2.0.conv1.conv.weight
backbone.layer2.0.conv1.bn.weight
backbone.layer2.0.conv1.bn.bias
backbone.layer2.0.conv1.bn.running_mean
backbone.layer2.0.conv1.bn.running_var
backbone.layer2.0.conv1.bn.num_batches_tracked
backbone.layer2.0.conv2.conv.weight
backbone.layer2.0.conv2.bn.weight
backbone.layer2.0.conv2.bn.bias
backbone.layer2.0.conv2.bn.running_mean
backbone.layer2.0.conv2.bn.running_var
backbone.layer2.0.conv2.bn.num_batches_tracked
backbone.layer2.0.conv3.conv.weight
backbone.layer2.0.conv3.bn.weight
backbone.layer2.0.conv3.bn.bias
backbone.layer2.0.conv3.bn.running_mean
backbone.layer2.0.conv3.bn.running_var
backbone.layer2.0.conv3.bn.num_batches_tracked
backbone.layer2.0.downsample.conv.weight
backbone.layer2.0.downsample.bn.weight
backbone.layer2.0.downsample.bn.bias
backbone.layer2.0.downsample.bn.running_mean
backbone.layer2.0.downsample.bn.running_var
backbone.layer2.0.downsample.bn.num_batches_tracked
backbone.layer2.1.conv1.conv.weight
backbone.layer2.1.conv1.bn.weight
backbone.layer2.1.conv1.bn.bias
backbone.layer2.1.conv1.bn.running_mean
backbone.layer2.1.conv1.bn.running_var
backbone.layer2.1.conv1.bn.num_batches_tracked
backbone.layer2.1.conv2.conv.weight
backbone.layer2.1.conv2.bn.weight
backbone.layer2.1.conv2.bn.bias
backbone.layer2.1.conv2.bn.running_mean
backbone.layer2.1.conv2.bn.running_var
backbone.layer2.1.conv2.bn.num_batches_tracked
backbone.layer2.1.conv3.conv.weight
backbone.layer2.1.conv3.bn.weight
backbone.layer2.1.conv3.bn.bias
backbone.layer2.1.conv3.bn.running_mean
backbone.layer2.1.conv3.bn.running_var
backbone.layer2.1.conv3.bn.num_batches_tracked
backbone.layer2.2.conv1.conv.weight
backbone.layer2.2.conv1.bn.weight
backbone.layer2.2.conv1.bn.bias
backbone.layer2.2.conv1.bn.running_mean
backbone.layer2.2.conv1.bn.running_var
backbone.layer2.2.conv1.bn.num_batches_tracked
backbone.layer2.2.conv2.conv.weight
backbone.layer2.2.conv2.bn.weight
backbone.layer2.2.conv2.bn.bias
backbone.layer2.2.conv2.bn.running_mean
backbone.layer2.2.conv2.bn.running_var
backbone.layer2.2.conv2.bn.num_batches_tracked
backbone.layer2.2.conv3.conv.weight
backbone.layer2.2.conv3.bn.weight
backbone.layer2.2.conv3.bn.bias
backbone.layer2.2.conv3.bn.running_mean
backbone.layer2.2.conv3.bn.running_var
backbone.layer2.2.conv3.bn.num_batches_tracked
backbone.layer2.3.conv1.conv.weight
backbone.layer2.3.conv1.bn.weight
backbone.layer2.3.conv1.bn.bias
backbone.layer2.3.conv1.bn.running_mean
backbone.layer2.3.conv1.bn.running_var
backbone.layer2.3.conv1.bn.num_batches_tracked
backbone.layer2.3.conv2.conv.weight
backbone.layer2.3.conv2.bn.weight
backbone.layer2.3.conv2.bn.bias
backbone.layer2.3.conv2.bn.running_mean
backbone.layer2.3.conv2.bn.running_var
backbone.layer2.3.conv2.bn.num_batches_tracked
backbone.layer2.3.conv3.conv.weight
backbone.layer2.3.conv3.bn.weight
backbone.layer2.3.conv3.bn.bias
backbone.layer2.3.conv3.bn.running_mean
backbone.layer2.3.conv3.bn.running_var
backbone.layer2.3.conv3.bn.num_batches_tracked
backbone.layer2.4.conv1.conv.weight
backbone.layer2.4.conv1.bn.weight
backbone.layer2.4.conv1.bn.bias
backbone.layer2.4.conv1.bn.running_mean
backbone.layer2.4.conv1.bn.running_var
backbone.layer2.4.conv1.bn.num_batches_tracked
backbone.layer2.4.conv2.conv.weight
backbone.layer2.4.conv2.bn.weight
backbone.layer2.4.conv2.bn.bias
backbone.layer2.4.conv2.bn.running_mean
backbone.layer2.4.conv2.bn.running_var
backbone.layer2.4.conv2.bn.num_batches_tracked
backbone.layer2.4.conv3.conv.weight
backbone.layer2.4.conv3.bn.weight
backbone.layer2.4.conv3.bn.bias
backbone.layer2.4.conv3.bn.running_mean
backbone.layer2.4.conv3.bn.running_var
backbone.layer2.4.conv3.bn.num_batches_tracked
backbone.layer2.5.conv1.conv.weight
backbone.layer2.5.conv1.bn.weight
backbone.layer2.5.conv1.bn.bias
backbone.layer2.5.conv1.bn.running_mean
backbone.layer2.5.conv1.bn.running_var
backbone.layer2.5.conv1.bn.num_batches_tracked
backbone.layer2.5.conv2.conv.weight
backbone.layer2.5.conv2.bn.weight
backbone.layer2.5.conv2.bn.bias
backbone.layer2.5.conv2.bn.running_mean
backbone.layer2.5.conv2.bn.running_var
backbone.layer2.5.conv2.bn.num_batches_tracked
backbone.layer2.5.conv3.conv.weight
backbone.layer2.5.conv3.bn.weight
backbone.layer2.5.conv3.bn.bias
backbone.layer2.5.conv3.bn.running_mean
backbone.layer2.5.conv3.bn.running_var
backbone.layer2.5.conv3.bn.num_batches_tracked
backbone.layer3.0.conv1.conv.weight
backbone.layer3.0.conv1.bn.weight
backbone.layer3.0.conv1.bn.bias
backbone.layer3.0.conv1.bn.running_mean
backbone.layer3.0.conv1.bn.running_var
backbone.layer3.0.conv1.bn.num_batches_tracked
backbone.layer3.0.conv2.conv.weight
backbone.layer3.0.conv2.bn.weight
backbone.layer3.0.conv2.bn.bias
backbone.layer3.0.conv2.bn.running_mean
backbone.layer3.0.conv2.bn.running_var
backbone.layer3.0.conv2.bn.num_batches_tracked
backbone.layer3.0.conv3.conv.weight
backbone.layer3.0.conv3.bn.weight
backbone.layer3.0.conv3.bn.bias
backbone.layer3.0.conv3.bn.running_mean
backbone.layer3.0.conv3.bn.running_var
backbone.layer3.0.conv3.bn.num_batches_tracked
backbone.layer3.0.downsample.conv.weight
backbone.layer3.0.downsample.bn.weight
backbone.layer3.0.downsample.bn.bias
backbone.layer3.0.downsample.bn.running_mean
backbone.layer3.0.downsample.bn.running_var
backbone.layer3.0.downsample.bn.num_batches_tracked
backbone.layer3.1.conv1.conv.weight
backbone.layer3.1.conv1.bn.weight
backbone.layer3.1.conv1.bn.bias
backbone.layer3.1.conv1.bn.running_mean
backbone.layer3.1.conv1.bn.running_var
backbone.layer3.1.conv1.bn.num_batches_tracked
backbone.layer3.1.conv2.conv.weight
backbone.layer3.1.conv2.bn.weight
backbone.layer3.1.conv2.bn.bias
backbone.layer3.1.conv2.bn.running_mean
backbone.layer3.1.conv2.bn.running_var
backbone.layer3.1.conv2.bn.num_batches_tracked
backbone.layer3.1.conv3.conv.weight
backbone.layer3.1.conv3.bn.weight
backbone.layer3.1.conv3.bn.bias
backbone.layer3.1.conv3.bn.running_mean
backbone.layer3.1.conv3.bn.running_var
backbone.layer3.1.conv3.bn.num_batches_tracked
backbone.layer3.2.conv1.conv.weight
backbone.layer3.2.conv1.bn.weight
backbone.layer3.2.conv1.bn.bias
backbone.layer3.2.conv1.bn.running_mean
backbone.layer3.2.conv1.bn.running_var
backbone.layer3.2.conv1.bn.num_batches_tracked
backbone.layer3.2.conv2.conv.weight
backbone.layer3.2.conv2.bn.weight
backbone.layer3.2.conv2.bn.bias
backbone.layer3.2.conv2.bn.running_mean
backbone.layer3.2.conv2.bn.running_var
backbone.layer3.2.conv2.bn.num_batches_tracked
backbone.layer3.2.conv3.conv.weight
backbone.layer3.2.conv3.bn.weight
backbone.layer3.2.conv3.bn.bias
backbone.layer3.2.conv3.bn.running_mean
backbone.layer3.2.conv3.bn.running_var
backbone.layer3.2.conv3.bn.num_batches_tracked
cls_head.fc_cls.weight
cls_head.fc_cls.bias

"""