"""
backbone.data_bn.weight
backbone.data_bn.bias
backbone.data_bn.running_mean
backbone.data_bn.running_var
backbone.data_bn.num_batches_tracked
backbone.gcn.0.gcn.PA
backbone.gcn.0.gcn.A
backbone.gcn.0.gcn.bn.weight
backbone.gcn.0.gcn.bn.bias
backbone.gcn.0.gcn.bn.running_mean
backbone.gcn.0.gcn.bn.running_var
backbone.gcn.0.gcn.bn.num_batches_tracked
backbone.gcn.0.gcn.conv.weight
backbone.gcn.0.gcn.conv.bias
backbone.gcn.0.tcn.conv.weight
backbone.gcn.0.tcn.conv.bias
backbone.gcn.0.tcn.bn.weight
backbone.gcn.0.tcn.bn.bias
backbone.gcn.0.tcn.bn.running_mean
backbone.gcn.0.tcn.bn.running_var
backbone.gcn.0.tcn.bn.num_batches_tracked
backbone.gcn.1.gcn.PA
backbone.gcn.1.gcn.A
backbone.gcn.1.gcn.bn.weight
backbone.gcn.1.gcn.bn.bias
backbone.gcn.1.gcn.bn.running_mean
backbone.gcn.1.gcn.bn.running_var
backbone.gcn.1.gcn.bn.num_batches_tracked
backbone.gcn.1.gcn.conv.weight
backbone.gcn.1.gcn.conv.bias
backbone.gcn.1.tcn.conv.weight
backbone.gcn.1.tcn.conv.bias
backbone.gcn.1.tcn.bn.weight
backbone.gcn.1.tcn.bn.bias
backbone.gcn.1.tcn.bn.running_mean
backbone.gcn.1.tcn.bn.running_var
backbone.gcn.1.tcn.bn.num_batches_tracked
backbone.gcn.2.gcn.PA
backbone.gcn.2.gcn.A
backbone.gcn.2.gcn.bn.weight
backbone.gcn.2.gcn.bn.bias
backbone.gcn.2.gcn.bn.running_mean
backbone.gcn.2.gcn.bn.running_var
backbone.gcn.2.gcn.bn.num_batches_tracked
backbone.gcn.2.gcn.conv.weight
backbone.gcn.2.gcn.conv.bias
backbone.gcn.2.tcn.conv.weight
backbone.gcn.2.tcn.conv.bias
backbone.gcn.2.tcn.bn.weight
backbone.gcn.2.tcn.bn.bias
backbone.gcn.2.tcn.bn.running_mean
backbone.gcn.2.tcn.bn.running_var
backbone.gcn.2.tcn.bn.num_batches_tracked
backbone.gcn.3.gcn.PA
backbone.gcn.3.gcn.A
backbone.gcn.3.gcn.bn.weight
backbone.gcn.3.gcn.bn.bias
backbone.gcn.3.gcn.bn.running_mean
backbone.gcn.3.gcn.bn.running_var
backbone.gcn.3.gcn.bn.num_batches_tracked
backbone.gcn.3.gcn.conv.weight
backbone.gcn.3.gcn.conv.bias
backbone.gcn.3.tcn.conv.weight
backbone.gcn.3.tcn.conv.bias
backbone.gcn.3.tcn.bn.weight
backbone.gcn.3.tcn.bn.bias
backbone.gcn.3.tcn.bn.running_mean
backbone.gcn.3.tcn.bn.running_var
backbone.gcn.3.tcn.bn.num_batches_tracked
backbone.gcn.4.gcn.PA
backbone.gcn.4.gcn.A
backbone.gcn.4.gcn.bn.weight
backbone.gcn.4.gcn.bn.bias
backbone.gcn.4.gcn.bn.running_mean
backbone.gcn.4.gcn.bn.running_var
backbone.gcn.4.gcn.bn.num_batches_tracked
backbone.gcn.4.gcn.conv.weight
backbone.gcn.4.gcn.conv.bias
backbone.gcn.4.tcn.conv.weight
backbone.gcn.4.tcn.conv.bias
backbone.gcn.4.tcn.bn.weight
backbone.gcn.4.tcn.bn.bias
backbone.gcn.4.tcn.bn.running_mean
backbone.gcn.4.tcn.bn.running_var
backbone.gcn.4.tcn.bn.num_batches_tracked
backbone.gcn.4.residual.conv.weight
backbone.gcn.4.residual.conv.bias
backbone.gcn.4.residual.bn.weight
backbone.gcn.4.residual.bn.bias
backbone.gcn.4.residual.bn.running_mean
backbone.gcn.4.residual.bn.running_var
backbone.gcn.4.residual.bn.num_batches_tracked
backbone.gcn.5.gcn.PA
backbone.gcn.5.gcn.A
backbone.gcn.5.gcn.bn.weight
backbone.gcn.5.gcn.bn.bias
backbone.gcn.5.gcn.bn.running_mean
backbone.gcn.5.gcn.bn.running_var
backbone.gcn.5.gcn.bn.num_batches_tracked
backbone.gcn.5.gcn.conv.weight
backbone.gcn.5.gcn.conv.bias
backbone.gcn.5.tcn.conv.weight
backbone.gcn.5.tcn.conv.bias
backbone.gcn.5.tcn.bn.weight
backbone.gcn.5.tcn.bn.bias
backbone.gcn.5.tcn.bn.running_mean
backbone.gcn.5.tcn.bn.running_var
backbone.gcn.5.tcn.bn.num_batches_tracked
backbone.gcn.6.gcn.PA
backbone.gcn.6.gcn.A
backbone.gcn.6.gcn.bn.weight
backbone.gcn.6.gcn.bn.bias
backbone.gcn.6.gcn.bn.running_mean
backbone.gcn.6.gcn.bn.running_var
backbone.gcn.6.gcn.bn.num_batches_tracked
backbone.gcn.6.gcn.conv.weight
backbone.gcn.6.gcn.conv.bias
backbone.gcn.6.tcn.conv.weight
backbone.gcn.6.tcn.conv.bias
backbone.gcn.6.tcn.bn.weight
backbone.gcn.6.tcn.bn.bias
backbone.gcn.6.tcn.bn.running_mean
backbone.gcn.6.tcn.bn.running_var
backbone.gcn.6.tcn.bn.num_batches_tracked
backbone.gcn.7.gcn.PA
backbone.gcn.7.gcn.A
backbone.gcn.7.gcn.bn.weight
backbone.gcn.7.gcn.bn.bias
backbone.gcn.7.gcn.bn.running_mean
backbone.gcn.7.gcn.bn.running_var
backbone.gcn.7.gcn.bn.num_batches_tracked
backbone.gcn.7.gcn.conv.weight
backbone.gcn.7.gcn.conv.bias
backbone.gcn.7.tcn.conv.weight
backbone.gcn.7.tcn.conv.bias
backbone.gcn.7.tcn.bn.weight
backbone.gcn.7.tcn.bn.bias
backbone.gcn.7.tcn.bn.running_mean
backbone.gcn.7.tcn.bn.running_var
backbone.gcn.7.tcn.bn.num_batches_tracked
backbone.gcn.7.residual.conv.weight
backbone.gcn.7.residual.conv.bias
backbone.gcn.7.residual.bn.weight
backbone.gcn.7.residual.bn.bias
backbone.gcn.7.residual.bn.running_mean
backbone.gcn.7.residual.bn.running_var
backbone.gcn.7.residual.bn.num_batches_tracked
backbone.gcn.8.gcn.PA
backbone.gcn.8.gcn.A
backbone.gcn.8.gcn.bn.weight
backbone.gcn.8.gcn.bn.bias
backbone.gcn.8.gcn.bn.running_mean
backbone.gcn.8.gcn.bn.running_var
backbone.gcn.8.gcn.bn.num_batches_tracked
backbone.gcn.8.gcn.conv.weight
backbone.gcn.8.gcn.conv.bias
backbone.gcn.8.tcn.conv.weight
backbone.gcn.8.tcn.conv.bias
backbone.gcn.8.tcn.bn.weight
backbone.gcn.8.tcn.bn.bias
backbone.gcn.8.tcn.bn.running_mean
backbone.gcn.8.tcn.bn.running_var
backbone.gcn.8.tcn.bn.num_batches_tracked
backbone.gcn.9.gcn.PA
backbone.gcn.9.gcn.A
backbone.gcn.9.gcn.bn.weight
backbone.gcn.9.gcn.bn.bias
backbone.gcn.9.gcn.bn.running_mean
backbone.gcn.9.gcn.bn.running_var
backbone.gcn.9.gcn.bn.num_batches_tracked
backbone.gcn.9.gcn.conv.weight
backbone.gcn.9.gcn.conv.bias
backbone.gcn.9.tcn.conv.weight
backbone.gcn.9.tcn.conv.bias
backbone.gcn.9.tcn.bn.weight
backbone.gcn.9.tcn.bn.bias
backbone.gcn.9.tcn.bn.running_mean
backbone.gcn.9.tcn.bn.running_var
backbone.gcn.9.tcn.bn.num_batches_tracked
cls_head.fc_cls.weight
cls_head.fc_cls.bias

"""